### ISSUE TITLE
Failed to run `credhub api`, NPE reported on the credhub server side

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry-incubator/credhub#16]
CredHub server (together with postgres and uaa) was setup up using sample yml https://github.com/pivotal-cf/credhub-release/blob/master/sample-manifests/credhub-postgres-uaa.yml

Releases used:
```releases:
- name: credhub
  url: https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=1.3.0
  version: 1.3.0
  sha1: 2b13fa390bd1b0ec7ca69537d1ac67b101cf0f7d
- name: postgres
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=20
  version: 20
  sha1: 3f378bcab294e20316171d4e656636df88763664
- name: uaa
  url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=45
  version: 45
  sha1: 4d4fba13b724b75206f5eb3abae8efa94dcf7db8
```

Credhub Cli (version 1.4.1) was downloaded to another VM.

Failed to run `credhub api` command:
```
# credhub api https://<CredHub_server_ip>:8844/api/ --ca-cert credhub-ca.pem
The targeted API does not appear to be valid. Please validate the API address and retry your request.
```

On the CredHub server side, `/var/vcap/sys/log/credhub/credhub.log` reported error:
```2017-08-25T07:05:16.634Z [https-jsse-nio-8844-exec-10] .... ERROR --- HandlerExecutionChain: HandlerInterceptor.afterCompletion threw exception
java.lang.NullPointerException: null
	at io.pivotal.security.auth.UserContextFactory.createUserContext(UserContextFactory.java:35) ~[classes!/:?]
	at io.pivotal.security.auth.UserContextFactory.createUserContext(UserContextFactory.java:30) ~[classes!/:?]
	at io.pivotal.security.audit.AuditInterceptor.afterCompletion(AuditInterceptor.java:56) ~[classes!/:?]
	at org.springframework.web.servlet.HandlerExecutionChain.triggerAfterCompletion(HandlerExecutionChain.java:169) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1059) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.16.jar!/:8.5.16]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```

Is there any problem? Anyway, NPE should not be reported.

**Comment by pivotal-danjahner** [comment]
@gu-bin Hello - When targeting CredHub, you only need to specify the hostname and port, no additional paths.

Updating your request `credhub api https://<CredHub_server_ip>:8844/api/ --ca-cert credhub-ca.pem` to `credhub api https://<CredHub_server_ip>:8844 --ca-cert credhub-ca.pem` should target appropriately.

**Comment by gu-bin** [comment]
When I changed to `credhub api https://<CredHub_server_ip>:8844 --ca-cert credhub-ca.pem`, I got this error:
`Get https://127.0.0.1:8443/info: dial tcp 127.0.0.1:8443: getsockopt: connection refused`
